Resources:
  resumeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: contacts-dev-userresumebucket
  resumeBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket:
        Ref: "resumeBucket"
      PolicyDocument:
        Statement:
          -
            Effect: "Allow"
            Principal: "*"
            Action:
              - "s3:GetObject"
            Resource:
              Fn::Join:
                - ""
                - 
                  - "arn:aws:s3:::"
                  - 
                    Ref: "resumeBucket"
                  - "/*"
 